import "./globals.css";

export const metadata = {
  title: "Create A Saas App For Freelance Client Management With Auth",
  description: "Generated by AI SaaS Factory",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
